### ISSUE TITLE
Missing bash script

### ISSUE THREAD

**Issue by YolandiSwart** [hennlab/snake-SNP_QC#1]
Hi, I'm currently running the Snakemake pipeline for my H3Africa array data generated from Genomestudio. But there is no global_concordance.sh script in the scripts section required for the pipeline. Therefore, I keep on getting the following error: 

![image](https://user-images.githubusercontent.com/49681556/120790938-dacffd80-c533-11eb-8376-458d5bdfec6f.png)

**Comment by miramastoras** [comment]
Thank you for catching this! I apologize for not seeing this sooner. The script is now located in the scripts folder.
